### ISSUE TITLE
请问大佬

### ISSUE THREAD

**Issue by 546554574** [PopFisher/AccessibilitySample#1]
请问大佬，微信是怎么让AccessibilityEvent无效的

**Comment by PopFisher** [comment]
这是个好问题，要搞清楚怎么不让辅助生效，就要搞清楚辅助功能事件是怎么产生的。跟踪一下View 的源码，可以发现里面有发送辅助功能事件的代码 View.sendAccessibilityEvent(int eventType)。所以能想到的一招就是自定义一个View把辅助功能相关的方法给拦截了或者就根本不产生辅助功能都事件。微信好像也不是所有地方都不让你用辅助功能，也是在一些关键位置给拦截了一下。

**Comment by 546554574** [comment]
谢谢大佬
